vippsas/vipps-recurring-api

vipps-recurring-api.md

Changes in abstract, typical flow, charge retries and added HTTP 422 error.

Minor updates to the description of the product

---

docs/swagger.yaml

Reading blind on the logic of time, so please review 📆

added range to due date

---

README.md

Slack: "Christian Løverås [6:06 PM]
Recurring: Quarterly should be every third, not fourth, month, right?"

Correct intervalCount in interval example.

---

vipps-recurring-api.md

- Added newlines to the "4. Manage charges and agreements with" to improve readability.
- Added "json" to all code snippets with json data for consistency.

Some changes for readability. Added code type to code snippets.

---

docs/swagger.yaml

Update link to Authentication

---

docs/swagger.yaml

- Examples, patterns and lengths for MSN, Authorization, etc
- Cancel charge: DELETE does not return the deleted charge (less chatty)
- Refund charge: Does not return a charge (less chatty)
- List charges: Enums for status filtering
- Shorter descriptions of operations
- Idempotency-Key, not Idempotent-Key (to match other APIs)
- Cancel charge: Added Idempotency-Key
Preview: https://recurring-wip.restlet.io
TODO:
- Cancel charge: Should it return 200 and no content? Need to remove 200 or 204 response.

Changes after review in Restlet

---

docs/swagger.yaml

Reverts vippsas/vipps-recurring-api#48

Revert "Changes after review in Restlet"

---

docs/swagger.yaml

Reverts vippsas/vipps-recurring-api#47

Revert "Plural, request/object, misc"

---

vipps-recurring-api.md

Reverts vippsas/vipps-recurring-api#46

Revert "Changed description of POST:/charge/{agreementId} overview"

---

docs/index.html
docs/openapi.yaml
vipps-recurring-api.md

Updates vipp-recurring-api.md with new V2 api changes.
#49 #56

V2 updates

---

tools/vipps-recurring-api-postman-collection.json
tools/vipps-recurring-api-postman-environment.json

Reverts vippsas/vipps-recurring-api#58

Revert "Update postman collection to use V2"

---

README.md
vipps-recurring-api-checklist.md
vipps-recurring-api-faq.md
vipps-recurring-api.md

* Changed links so they open the the correct endpoints in https://vippsas.github.io/vipps-recurring-api/#/ 
* Fixed some spelling

Changed links

---

vipps-recurring-api.md

Added recommendations for merchants on how to handle agreement life cycle. 
Added separate sub section under Step 4: Manage charges and agreements

Agreement life cycle recommendations

---

vipps-recurring-api.md

Updated info about logic around retry days

Updated info about logic around retry days

---

vipps-recurring-api.md

Updated documentation on status of charges during retry period

Updated documentation

---

vipps-recurring-api.md

Slack thread: https://vippsas.slack.com/archives/C8HP1AJ79/p1612334492158200

Added: orderId recommendations

---

vipps-recurring-api-faq.md

Just updated info so that it covers initial charges and covers info from merchant perspective.
Checked details with product owner.

Changed info about what happens to charges when agreement is stopped

---

vipps-recurring-postman.md

Copied from eCom: https://github.com/vippsas/vipps-ecom-api/blob/master/vipps-ecom-postman.md
With some very minor changes. 
TODO: Make the "Run in Postman" button work.

Added Postman guide

---

vipps-recurring-api.md

as it does not reflect what the actual flow is/should be.

Rephrasing the call-by-call guide, 

---

vipps-recurring-api.md

Added tips and guidelines for use of campaigns vs initial charge

Added tips and guidelines

---

docs/openapi.yaml
vipps-recurring-api.md

I was still working on the content type branch. Well-well.

Scopoe without s everywhere

---

vipps-recurring-api-checklist.md

Similar to https://github.com/vippsas/vipps-ecom-api/blob/master/vipps-ecom-api-checklist.md

More self-service

---

docs/openapi.yaml

Update OAS spec with latest changes

---

vipps-recurring-api.md

Updating info about when we process charges, as well as added a note that we might process charges outside these times in some cases (problems with payment providers etc)

Updating info about when we process charges

---

vipps-recurring-api.md

some text changes to describe recurring with variable  amount

small text changes

---

docs/openapi.yaml

Add force accept agreement endpoint to OpenAPI docs

---

vipps-recurring-api.md

https://vippsas.slack.com/archives/CCKFJE3SA/p1632909502062900

Added info about charge states

---

vipps-recurring-api.md

Try to improve explanation of charge flows, fix some inaccuracies

Add details about charge flows

---

tools/vipps-recurring-api-postman-collection.json
tools/vipps-recurring-api-postman-environment.json

Added vipps headers to postman environment and to the header of each endpoint.
The postman export also included changes to the json structure.

Added vipps headers to postman

---

docs/openapi.yaml

Proposal / draft.
See (internal): https://jira.vipps.iobrowse/VSD-13283

Added `nullable` for improved codegen

---

docs/openapi.yaml

Added new v3 (under development) charge endpoints
Changed structure and errors

Improvements to the swagger

---

vipps-recurring-api-faq.md
vipps-recurring-api-howitworks.md
vipps-recurring-api.md

The only thing that is not trivial is in the introduction section. See it rendered here: https://github.com/vippsas/vipps-recurring-api/blob/2687f70ede4ed65d00e2483d1c3c25dfe7e8fcd2/vipps-recurring-api.md

Polishing first part of recurring api guide

---

vipps-recurring-api-faq.md
vipps-recurring-api.md

Changing some links to refer to the Common topics instead of to eCom.
Also, fixing some broken links.

Updating links

---

docs/openapi.yaml
vipps-recurring-api.md

Add info about Continuation-Token headers to the documentation

Tre 747 748 continuation token headers

---

vipps-recurring-api.md

Add some info about how you need initial charge to require payment for agreement activation, and improve the description of what an agreement is.

Add some info about initial charge.

---

docs/openapi.yaml

It is now in a separate swagger --> https://vippsas.github.io/vipps-developer-docs/api/access-token

Remove get access token from recurring swagger

---

vipps-recurring-api.md

- Note -> Please note
- Some typos
- Moved some text about retries

Clarifications + tweaks

---

v2-to-v3-migration-guide.md
vipps-recurring-api-faq.md
vipps-recurring-api-quick-start.md
vipps-recurring-api.md

Docusaurus reports the slash as 404 before redirecting

Correct more links to remove the trailing slash

---

vipps-recurring-api.md

Added a tiny section so it shows up in the ToC.
Background: https://vippsas.slack.com/archives/C02DT0370E8/p1676460283336599

Refund section

---

vipps-recurring-api.md

An attempt at making it clearer how to get access to the API.

Order info details

---

docs/openapi.yaml
vipps-recurring-api-faq.md
vipps-recurring-api-problems.md
vipps-recurring-api.md

Debated here: https://vippsas.slack.com/archives/C8HP1AJ79/p1677679961577569?thread_ts=1677672538.118429&cid=C8HP1AJ79

Update "sale unit" to "sales unit" in all repos

---

vipps-recurring-api-checklist.md
vipps-recurring-api-quick-start.md

Fixes a download issue on developer.vippsmobilepay.com

CI-2251: Make links to downloadable files absolute

---

vipps-recurring-api-faq.md
vipps-recurring-api-problems.md
vipps-recurring-api-quick-start.md
vipps-recurring-api.md

This should be trivial fixes for errors discovered by my LTeX tool. I also worked on one of the FAQs a bit. The translated FAQ is in another PR https://github.com/vippsas/vipps-recurring-api/pull/356.

Fix grammar and lint errors

---

vipps-recurring-api-checklist.md

This is a refactored version of the checklist. It is the same content, but has been updated to match the new format for all the APIs.

Refactor checklist

---

vipps-recurring-api-faq.md

It seems this should be in English, although it also seems to repeat some of what is below. Could you please have a look and update it as it should be. :-) Google Translate didn't know what "trekk" was in this case. I wasn't sure either, but I think it was a "charge". :-)

Possible translation

---

vipps-recurring-api-postman-guide.md
vipps-recurring-api-quick-start.md

Update quick start guides to lead people to getting started and give information about not using production keys in postman

Update quick start guides

---

CHANGELOG.md
README.md
docs/openapi.yaml
vipps-recurring-api-faq.md
vipps-recurring-api-postman-guide.md
vipps-recurring-api.md

Rebranding: "Vipps MobilePay app" to "Vipps or MobilePay app"
Add Recurring plugins

"Vipps MobilePay app" to "Vipps or MobilePay app"

---

vipps-recurring-api.md

People have complained about these. There a lot more of them in the eCom guide (my own fault). 😬😬

This tries to address sections with just redirects to other sections

---

docs/openapi.yaml

Clarified: orderId and chargeId
